services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${S3_ENDPOINT}
    volumes:
      - ./docker-data/minio:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: [CMD, mc, ready, local]
      interval: 30s
      timeout: 20s
      retries: 3

  mongo:
    container_name: mongo
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    #      MONGO_INITDB_DATABASE: init
    volumes:
      - ./docker-data/mongo:/data/db/
      - /etc/timezone:/etc/timezone:ro

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
